<?php
$conf=array (
  'siteName' => '我的博客',
  'siteURL' => 'http://bwblog',
  'authorName' => 'sct',
  'authorIntro' => '使用bW创建',
  'siteKey' => '82863c7da7d2fc538ee25ca808f27b211682b595',
  'timeZone' => 'Asia/Shanghai',
  'pageCache' => '0',
  'commentOpt' => '0',
  'comFrequency' => '10',
  'comPerLoad' => '20',
  'siteTheme' => 'default',
  'siteLang' => 'zh-cn',
  'perPage' => '3',
  'linkPrefixIndex' => 'index.php',
  'linkPrefixCategory' => 'category.php',
  'linkPrefixArticle' => 'read.php',
  'linkPrefixTag' => 'tag.php',
  'social-sina-weibo' => '',
  'social-weixin' => '',
  'social-twitter' => '',
  'social-facebook' => '',
  'social-douban' => '',
  'social-instagram' => '',
  'social-renren' => '',
  'social-linkedin' => '',
  'externalLinks' => 'http://bw.bo-blog.com=bW Home',
);